import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./api/auth/Provider";
import SideBar from "./components/SideBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "DW-Zwinger von der Huht",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="huhtTheme">
      <body className={inter.variable}>
        <AuthProvider>
          <SideBar>{children}</SideBar>
        </AuthProvider>
      </body>
    </html>
  );
}
