import Footer from "@/app/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/app/components/NavBar";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "DW-Zwinger von der Huht",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="huhtTheme">
      <body className={inter.variable}>
        <NavBar />
        <div id="content-wrapper" className="flex flex-col min-h-screen">
          <div className="flex-grow px-12 py-5 sm:px-24 md:px-30 lg:px-40 lg:py-10">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
